[package]
name = "multichannel_audio_bin"
version = "0.2.1"
edition = "2021"

[dependencies]
multichannel_audio = { path = "../multichannel_audio" }

[[bin]]
name = "multichannel_audio_bin"
path = "src/main.rs"
