name: Publish to crates.io
on:
    pull_request: {}
    push:
        branches: 
            - main

jobs:
    cargo_publish_dry_run:
        runs-on: ubuntu-latest
        timeout-minutes: 10
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable

            - name: Install libasound2-dev
              run: sudo apt-get install libasound2-dev

            - name: cargo Login
              run: cargo login ${{ secrets.CRATES_IO_API_KEY }}

            - name: cargo Publish
              run: cargo publish --dry-run -p multichannel_audio

    build_and_publish:
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        runs-on: ubuntu-latest
        timeout-minutes: 10
        needs: cargo_publish_dry_run
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable

            - name: Install libasound2-dev
              run: sudo apt-get install libasound2-dev

            - name: cargo Login
              run: cargo login ${{ secrets.CRATES_IO_API_KEY }}

            - name: cargo Publish
              run: cargo publish -p multichannel_audio